### ISSUE TITLE
realizeCascades is overly verbose

### ISSUE THREAD

**Issue by gerudo7** [villano-lab/nrCascadeSim#12]
From **matthewfeickert** in `openjournals/joss-reviews#3174` on 04/29/21
> the command
`./bin/realizeCascades -o output.root levelfiles/Si28_ngam_all_cascades_rfmt_sorted.txt`
prints output to stdout by default with no additional logging, which makes it quite difficult to digest the relevant information. It would be good if this could be made a non-default option.

**Description:** It is difficult to determine what information is relevant because too much is printed.
**Solution:** Reduce the amount of information printed to stdout when running realizeCascades
**Testing:** N/A

**Comment by villaa** [comment]
@gerudo7 I think the verbosity flag was implemented incorrectly, it seems to only write cascades when the verbosity flag is given, and I missed this in the code review. We want it to write the cascades in any case; that is the line 

```

cri *cascade_data;
                cascade_data = Cascade(nrealize,cascadeFile[k].cid,cascadeFile[k].Sn,cascadeFile[k].n,cascadeFile[k].Elev,cascadeFile[k].taus,cascadeFile[k].A,mtrand);
```

Or maybe did I put that in the verbosity if statement when I was editing something else? Who knows, but we should do a hotfix to fix it probably.
