### ISSUE TITLE
using automake to customize installation

### ISSUE THREAD

**Issue by villaa** [villano-lab/nrCascadeSim#26]
This  would be a cleaner way to do the installation currently. Check out [this](https://stackoverflow.com/questions/3239343/make-install-but-not-to-default-directories) SO post for info.

**Comment by gerudo7** [comment]
Superceded by #64 as both resolve the same issue, but CMake is a more modern way of resolving it.

**Comment by villaa** [comment]
Implemented CMake in PR #91 making this issue obsolete.
