### ISSUE TITLE
[JOSS Review]: Clarify units of input values in functions

### ISSUE THREAD

**Issue by altavir** [villano-lab/nrCascadeSim#74]
The units for masses and energies should be clarified in method documentation. Like here:
https://github.com/villano-lab/nrCascadeSim/blob/4f349d1de796e099db4af9f381b8ece16c894f33/src/cascadeProd.c#L459

It looks like the energy is in eV, but the mass in GeV, which is a bit confusing without documentation.

**Comment by villaa** [comment]
resolved by #78
