### ISSUE TITLE
[JOSS Review] Remove `.gcno` and `.gcda` files during the `clean` target.

### ISSUE THREAD

**Issue by gerudo7** [villano-lab/nrCascadeSim#84]
From the review thread: 
> Add removal of the .gcno and .gcda files generated during the build to the clean Make target.
Clean target should get rid of all generated files; these weren't added to the clean target when these files were introduced.

**Comment by matthewfeickert** [comment]
From: https://github.com/openjournals/joss-reviews/issues/3993#issuecomment-1015075303

When the default Make target

https://github.com/villano-lab/nrCascadeSim/blob/bf4795d83f8be6c9c1d737f5f51741def32cceb5/Makefile#L33

is run, it can generate [`.gcno` and `.gcda` files](https://gcc.gnu.org/onlinedocs/gcc/Gcov-Data-Files.html) that after compilation are artifacts. These should get added for removal in the `clean` Make target

https://github.com/villano-lab/nrCascadeSim/blob/bf4795d83f8be6c9c1d737f5f51741def32cceb5/Makefile#L86-L99

**Comment by villaa** [comment]
Now that we've moved to CMake try [this link](https://stackoverflow.com/questions/25963571/add-gcno-and-gcda-files-to-the-make-clean-rule-using-cmake).

**Comment by villaa** [comment]
In CMake can't set clean target well and the above link _doesn't_ do the cleaning upon _make clean_ but before the next build. 

However could try the solution suggested in these links:  [1](https://stackoverflow.com/questions/3925600/cmake-custom-clean-commands),  [2](https://cmake.org/cmake/help/v2.8.8/cmake.html#command%3aset_directory_properties). 

Basically, this would be to use the `set_directory_properties` to add `*.gcda` to the list of files that are removed on make clean.

**Comment by villaa** [comment]
@gerudo7 showed me [this reference](https://discourse.cmake.org/t/extending-generated-property-to-additional-compiler-output-files/432) for suggestions on cleaning up these kinds of files.

**Comment by villaa** [comment]
Trying to borrow stuff from [this reference](https://jhbell.com/using-cmake-and-gcov) too.

**Comment by villaa** [comment]
Fixed with PR #99
