### ISSUE TITLE
[JOSS Review] [JOSS Paper] Discuss whether software being compared to is open source.

### ISSUE THREAD

**Issue by gerudo7** [villano-lab/nrCascadeSim#86]
From the review thread:
> In the State of the Field section it would be beneficial to mention that Genat4 is open source software and to clarify if FIFRELIN is open source or not.

I don't know whether FIFRELIN is open-source or not and couldn't find any kind of download from a quick search (and can't currently access the reference provided for it). Pinging @villaa as he probably knows.

**Comment by villaa** [comment]
> From the review thread:
> 
> > In the State of the Field section it would be beneficial to mention that Genat4 is open source software and to clarify if FIFRELIN is open source or not.
> 
> I don't know whether FIFRELIN is open-source or not and couldn't find any kind of download from a quick search (and can't currently access the reference provided for it). Pinging @villaa as he probably knows.

@gerudo7 
I don't think FIFRELIN is open source, or, at least it's very hard to get your hands on (I tried). I can ask an author of one of the papers that uses it.  I would suggest we just mention and cite FIFRELIN as we already have and focus our main comparison with the well-known open-source [Geant4](https://geant4.web.cern.ch/) package. 

Also FIFRELIN wasn't originally designed to do exactly what we're doing, it was a nuclear evaporation code that has been modified and now [some groups](https://iopscience.iop.org/article/10.1088/1748-0221/16/07/P07032/pdf) are using it to investigate nuclear recoils after capture from heavy and intermediate nuclei and we are currently focusing on light nuclei.

**Comment by villaa** [comment]
Did this while writing up comparison with G4 in PR #98
