### ISSUE TITLE
[JOSS Review] Migrate Away from Travis-CI

### ISSUE THREAD

**Issue by nuclearGoblin** [villano-lab/nrCascadeSim#88]
From the review thread: 
> Migrate off of Travis CI. Travis CI has decided it will no longer offer free testing to the open source community and the 10,000 credits it gives users on the free trial plan should be viewed as an off ramp to ensure that there is robust CI support. As mentioned in #10, alternatives that are easy to switch to are GitHub Actions or Azure Pipelines.

**Comment by matthewfeickert** [comment]
From https://github.com/openjournals/joss-reviews/issues/3993#issuecomment-1015075303:

(This is a suggested improvement, but not a change that needs to be made to pass review).

While changing CI providers is not something that is relevant for this review, it should be noted that Travis CI now (2020 onwards) [offers a open source projects a one time non-renewable 10,000 build credit](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing).

If you're trying to decide between GitHub Actions and Azure Pipelines I would just go for whatever one makes the most sense to your brain. At the end of the day they all end up running on the same hardware as GitHub Actions jobs run on Azure Pipelines infrastructure.

**Comment by nuclearGoblin** [comment]
This is almost ready, just need to get the macos-11 build working. Currently there seems to be some kind of compatibility issue between the precompiled ROOT binaries and the base enviornment provided by the runner, which I've been trying to debug.

**Comment by nuclearGoblin** [comment]
Note: While Github Actions is set up now, we will also be looking into other options (CircleCI?) to keep the support for older operating systems before merging this branch.
