### ISSUE TITLE
[JOSS Review] Enable versioning of docs on ReadTheDocs

### ISSUE THREAD

**Issue by matthewfeickert** [villano-lab/nrCascadeSim#89]
(This is a suggested improvement, but not a change that needs to be made to pass review).

From https://github.com/openjournals/joss-reviews/issues/3993#issuecomment-1015075303:

> * The [docs on ReadTheDocs](https://nrcascadesim.readthedocs.io/) are not versioned beyond `latest` and `stable`. It would be great to see releases have versioned docs on ReadTheDocs too.

ReadTheDocs allows for easily providing versioned docs that match releases. This can be enabled on the project page. c.f. RTD's [Versioned Documentation page](https://docs.readthedocs.io/en/stable/versions.html) for more.

**Comment by gerudo7** [comment]
Think I got to this just before you posted it here -

> There are now doc versions for each minor version since we started using readthedocs (v1.2 and v1.3). Creating doc versions has also been added to the release checklist (3bc21dc).

_Originally posted by `@gerudo7` in #83_
