### ISSUE TITLE
CONTRIBUTING.md Missing

### ISSUE THREAD

**Issue by gerudo7** [villano-lab/nrCascadeSim#9]
From **matthewfeickert** in `openjournals/joss-reviews#3174` on 04/29/21
> 	There is no CONTRIBUTING.md, no descriptions of using GitHub Issues for bug tracking, no description of using GitHub Discussions, and also no code of conduct.

**Description:** CONTRIBUTING.md or something equivalent is non-existent.

**Solution:** Create a clear and complete document outlining use of GitHub issues, description of using GitHub discussions, and code of conduct.

**Testing:** N/A

**Comment by gerudo7** [comment]
There is now a placeholder CONTRIBUTING.md and **villaa** and I are collaborating on an outline for its contents.

**Comment by matthewfeickert** [comment]
While not required in the [JOSS review criteria for Community guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines) a Code of Conduct is a great thing to have.

**Comment by villaa** [comment]
As part of this I wonder if we can make a "ReleaseNotes.md" which are updated with staged release notes for the next release.

**Comment by villaa** [comment]
PR #19 resolves these issues.
